# Generated by Django 3.2.25 on 2024-12-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_department_nationality_student_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_registration',
            name='choice_One',
        ),
        migrations.RemoveField(
            model_name='applicant_registration',
            name='choice_Three',
        ),
        migrations.RemoveField(
            model_name='applicant_registration',
            name='choice_Two',
        ),
    ]
