# Generated by Django 3.2.25 on 2024-09-27 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_auto_20240409_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 19, 0, 22, 854408)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 19, 0, 22, 854408)),
        ),
    ]
